services:
  user-webmvc:
    build: .
    container_name: user-webmvc
    environment:
      - SERVER_PORT=8181
    ports:
      - "8181:8181"
    networks:
      - reactive-ms-network

networks:
  reactive-ms-network:
    external: true